/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import cookieManager from "strapi-plugin-cookie-manager/strapi-admin";
import navigation from "strapi-plugin-navigation/strapi-admin";
import netlifyDeployments from "strapi-plugin-netlify-deployments/strapi-admin";
import oembed from "strapi-plugin-oembed/strapi-admin";
import plausible from "strapi-plugin-plausible/strapi-admin";
import previewButton from "strapi-plugin-preview-button/strapi-admin";
import redirects from "strapi-plugin-redirects/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "color-picker": colorPicker,
    graphql: graphql,
    i18n: i18N,
    seo: seo,
    "users-permissions": usersPermissions,
    "cookie-manager": cookieManager,
    navigation: navigation,
    "netlify-deployments": netlifyDeployments,
    oembed: oembed,
    plausible: plausible,
    "preview-button": previewButton,
    redirects: redirects,
  },
});
